#!/bin/bash

################################################################################
# A Nagios Plugin that checks printers and their consumables, using SNMP.      #
#                                                                              #
# Copyright (C) 2016 Martin Brehmer <software@mbrehmer.de>                     #
#                                                                              #
# This program is free software; you can redistribute it and/or modify         #
# it under the terms of the GNU General Public License as published by         #
# the Free Software Foundation; either version 3, or (at your option)          #
# any later version.                                                           #
#                                                                              #
# This program is distributed in the hope that it will be useful,              #
# but WITHOUT ANY WARRANTY; without even the implied warranty of               #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                #
# GNU General Public License for more details.                                 #
#                                                                              #
# You should have received a copy of the GNU General Public License            #
# along with this program; if not, write to the Free Software Foundation,      #
# Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.           #
#                                                                              #
################################################################################

VERSION=1.0

STATE_OK=0
STATE_WARNING=1
STATE_CRITICAL=2
STATE_UNKNOWN=3
STATE_DEPENDENT=4

PROG_NAME=$(basename $0)

print_version()
{
	cat <<EOF
$PROG_NAME $VERSION

Copyright (C) 2016 Martin Brehmer <software@mbrehmer.de>

This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.
EOF
}

print_help()
{
	cat <<EOF
Usage: check_printer -p <PRINTER_IP> -c <COMMUNITY> -t <TEST>
                     [-V] [-h]

A Nagios Plugin that checks printers and their consumables, using SNMP.

Options:
   -h, --help                   	print this message
   -p, --printer <PRINTER_IP>   	IP address of the printer to test
   -c. --community <COMMUNITY>   the community string for the test
   -t, --test <TEST>             the test to do
   -V, --version                	print version information

values for<TEST> can be:
   MESSAGE           checks for messages
   MODEL             returns the model of the printer
   CONSUM_TEST       returns the names of all consumables
   CONSUM_ALL        checks all consumables at once
   CONSUM <String>   checks the status of the consumable with the name <String>
   PAPER1            checks the amount of paper in tray no. 1
   PAPER2            checks the amount of papaer in tray no.2
   PAPER3            checks the amount of papar in tray no.3
   PAGECOUNT         returns the count of sites printed
EOF
}
